Homework - modern cpp
coders-school/modern-cpp pull request #14
Opened 2020-10-11 10:15 UTC by anraf1001

2020-10-11 13:11 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-10-11 13:11 UTC, WBigaj commented on shapes/main.cpp
> +    if (*iter != nullptr) {
```suggestion
    if (*iter) {
```

2020-10-11 13:11 UTC, WBigaj commented on shapes/main.cpp
> +            cout << (it)->getArea() << std::endl;
```suggestion
        if (it) {
            cout << (it)->getArea() << std::endl;
        }
```

2020-10-11 13:11 UTC, WBigaj commented on shapes/main.cpp
> +            printShape(*it);
```suggestion
        if (it) {
            printShape(*it);
        }
```

2020-10-11 13:11 UTC, WBigaj commented on shapes/main.cpp
> +}};
```suggestion
    return s ? s->getArea() < x : false;
}};
```

2020-10-11 20:07 UTC, MaciejSalamonski approved these changes
Nice code 👍

2020-10-11 20:07 UTC, MaciejSalamonski commented on shapes/main.cpp
> +}};
+1

2020-10-12 21:52 UTC, jakjan95 approved these changes
For me code looks good, just some {} are missing, but that was not a homework task.

2020-10-27 12:39 UTC, ziobron requested changes
Only one this is missing - delegating constructors

2020-10-27 12:39 UTC, ziobron commented on shapes/Circle.hpp
> +    Circle(double r, Color color = Color::Green);
I do not see delegating constructors here. The idea was to leave the old constructor and call the new one in the olds' initialization list:

```suggestion
    Circle(double r) : Circle(r, Color::Green) {}
    Circle(double r, Color color);
```

calling constructor from it's own class was not allowed before C++14.
The same for other classes.

PS. I know that your version is more intuitive and does the same, but idea here is to learn how does delegating constructor works.

2020-10-28 11:55 UTC, ziobron approved these changes

2020-10-28 12:27 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-10-28 12:27 UTC, closed without merging