modern-cpp homework
coders-school/modern-cpp pull request #15
Opened 2020-10-11 20:00 UTC by jakjan95

Exercises: 11, 14, 15, 16, 17, 18
Author: @jakjan95

2020-10-11 20:11 UTC, MaciejSalamonski approved these changes
Good Job @jakjan95

2020-10-14 09:28 UTC, WBigaj reviewed
I have checked your code and have one complain.

2020-10-14 09:28 UTC, WBigaj commented on shapes/main.cpp
> +    for (const auto& it : collection)
I think you should fix formatting by adding bracets to oneliners,since it will make code more readable.

2020-10-28 12:34 UTC, ziobron requested changes
Missing delegating constructors. This feature allows you to call other constructor of your own class on constructors' initalizer list.

2020-10-28 12:34 UTC, ziobron commented on shapes/main.cpp
> +    return false; };
I don't like this formatting

2020-10-29 16:15 UTC, jakjan95 commented
Formatting issue fixed, added delegating constructors instead of constructors with default parameters :)

2020-10-29 16:49 UTC, ziobron approved these changes

2020-10-29 16:49 UTC, ziobron commented on shapes/Square.cpp
> +    : Rectangle(x, x, Color::Red) {}
this one is just a base class constructor call. Delegation takes place when you call other constructor of your own class.

2020-10-29 16:49 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-10-29 16:49 UTC, closed without merging