modern-cpp-Homework
coders-school/modern-cpp pull request #18
Opened 2020-10-16 15:57 UTC by Vicx95

Exercises: 11, 14, 15, 16, 17, 18
Author: @Vicx95

2020-10-17 01:32 UTC, MaciejSalamonski approved these changes
Everything seems to be ok i think. Nice code 👍

2020-10-17 06:09 UTC, jakjan95 approved these changes
For me code looks good +1

2020-10-22 10:29 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-10-22 10:29 UTC, WBigaj commented on shapes/main.cpp
> +            cout << it->getArea() << std::endl;
```suggestion
    for (const auto& it : collection) {
        if (it) {
            cout << it->getArea() << std::endl;
        }
    }
```

2020-10-22 10:29 UTC, WBigaj commented on shapes/main.cpp
> +            it->print();
```suggestion
    for (const auto& it : collection) {
        if (it) {
            it->print();
        }
    }
```

2020-10-22 10:29 UTC, WBigaj commented on shapes/main.cpp
>      return false;
```suggestion
    return s ? (s->getArea() < x) : false;
```

2020-10-22 10:29 UTC, WBigaj commented on shapes/main.cpp
>      return false;
```suggestion
    return s ? (s->getPerimeter() > 20) : false;
```

2020-10-22 10:29 UTC, WBigaj commented on shapes/main.cpp
>      return (first->getArea() < second->getArea());
```suggestion
    if (first == nullptr || second == nullptr) {
        return false;
    }
    return (first->getArea() < second->getArea());
```

2020-10-28 14:15 UTC, ziobron requested changes
Missing delegating constructors. This feature allows you to call other constructor from the same class on constructor's initalizer list.

2020-10-28 21:05 UTC, ziobron approved these changes

2020-10-28 21:06 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-10-28 21:06 UTC, closed without merging