modern cpp solution
coders-school/modern-cpp pull request #20
Opened 2020-10-21 21:34 UTC by marcindus

2020-10-22 07:18 UTC, MaciejSalamonski approved these changes

2020-10-22 07:18 UTC, MaciejSalamonski commented on shapes/Circle.cpp
> +
To mamy empty lines there

2020-10-22 07:18 UTC, MaciejSalamonski commented on shapes/main.cpp
> +    if (n <= 2)
Maybe let's use operator "?"

2020-10-22 07:21 UTC, MaciejSalamonski approved these changes
:+1:

2020-10-22 11:24 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-10-22 11:24 UTC, WBigaj commented on shapes/main.cpp
>              it->print();
```suggestion
    for (const auto& it : collection) {
        if (it) {
            it->print();
        }
    }
```

2020-10-22 11:24 UTC, WBigaj commented on shapes/main.cpp
>              cout << it->getArea() << std::endl;
```suggestion
    for (const auto& it : collection) {
        if (it) {
            cout << it->getArea() << std::endl;
        }
    }
```

2020-10-22 11:24 UTC, WBigaj commented on shapes/main.cpp
>          return 1;
```suggestion
```

2020-10-22 11:24 UTC, WBigaj commented on shapes/main.cpp
>      }
```suggestion
    }
    else
    {
        return fibo(n - 1) + fibo(n - 2);
    }
    return (n <= 2) ? 1 : (fibo(n - 1) + fibo(n - 2));
```

2020-10-22 11:24 UTC, WBigaj commented on shapes/main.cpp
>      }
Speaking of @MaciejSalamonski advice.

2020-10-28 14:32 UTC, ziobron requested changes
Everything is ok, but you have not used delegating constructors. This feature allow you to call other class constructor on constructor initalizer list. It wasn't allowed before C++14. You could only call Base class constructor.

2020-10-28 14:32 UTC, ziobron commented on shapes/main.cpp
> +std::shared_ptr<Shape> make_shape(Arguments&&... args);
forward declaration below actual function definition. To be deleted.

2020-10-28 21:37 UTC, marcindus commented
> Everything is ok, but you have not used delegating constructors. This feature allow you to call other class constructor on constructor initalizer list. It wasn't allowed before C++14. You could only call Base class constructor.

 I've added deleating constructor in Circle class: Base class shape constructor call:  Circle::Circle(double r, Color c = Color::Green) : r_(r), Shape(c)

2020-10-28 22:16 UTC, ziobron commented
> > Everything is ok, but you have not used delegating constructors. This feature allow you to call other class constructor on constructor initalizer list. It wasn't allowed before C++14. You could only call Base class constructor.
> 
> I've added deleating constructor in Circle class: Base class shape constructor call: Circle::Circle(double r, Color c = Color::Green) : r_(r), Shape(c)

It is not delegating constructor. It is calling a base class constructor. Constructor delegation is when you call constructor of the same class on the initalizer list of other constructor

https://www.geeksforgeeks.org/constructor-delegation-c/

2020-10-28 22:20 UTC, marcindus commented
> > > Everything is ok, but you have not used delegating constructors. This feature allow you to call other class constructor on constructor initalizer list. It wasn't allowed before C++14. You could only call Base class constructor.
> > 
> > 
> > I've added deleating constructor in Circle class: Base class shape constructor call: Circle::Circle(double r, Color c = Color::Green) : r_(r), Shape(c)
> 
> It is not delegating constructor. It is calling a base class constructor. Constructor delegation is when you call constructor of the same class on the initalizer list of other constructor
> 
> https://www.geeksforgeeks.org/constructor-delegation-c/

aaa, ok :)

2020-11-01 22:57 UTC, ziobron requested changes

2020-11-01 22:57 UTC, ziobron commented on shapes/Shape.hpp
> +    Color color_ = Color::Red;
it should stay private

2020-11-01 22:57 UTC, ziobron commented on shapes/Rectangle.cpp
> +Rectangle::Rectangle(Color c) : Rectangle()
we want to have such 2 constructors:
`Rectangle(double x, double y, Color c);  // already implemented`
`Rectangle(double x, double y);  // not implemented`
The latter should call the first one on it's initializer list.

2020-11-01 22:57 UTC, ziobron commented on shapes/Rectangle.cpp
> +    color_ = c;
you don't need to set it here. Use the constructor `Rectangle(double x, double y, Color c)`. Body will be empty.

2020-11-03 11:29 UTC, ziobron approved these changes

2020-11-03 11:30 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-11-03 11:30 UTC, closed without merging