Homework - Modern C++
coders-school/modern-cpp pull request #21
Opened 2020-10-23 19:53 UTC by MaciejSalamonski

2020-10-28 17:45 UTC, WBigaj approved these changes
I have checked your code and it looks good :)

2020-10-29 13:02 UTC, ziobron requested changes
Good, but delegating constructors are missing. This feature allows you to call constructor of the same class on constructor's initializer list.

2020-10-29 16:02 UTC, MaciejSalamonski commented
Delegating constructors added :)

2020-10-29 16:47 UTC, ziobron approved these changes

2020-10-29 16:47 UTC, ziobron commented on shapes/Square.cpp
> +    : Rectangle(x, x, Color::Green) {}
ok, but this one is not a delegation. You simply call a base class constructors here. Constructor delegation takes place when you call other constructor of your own class.

2020-10-29 16:48 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-10-29 16:48 UTC, closed without merging