homework Shapes
coders-school/modern-cpp pull request #23
Opened 2020-10-27 16:30 UTC by kari0036

2020-10-27 16:53 UTC, MaciejSalamonski approved these changes
:+1:

2020-10-28 17:48 UTC, WBigaj approved these changes
I have checked code and it looks good :)

2020-10-29 13:18 UTC, ziobron requested changes

2020-10-29 13:18 UTC, ziobron commented on shapes/Square.cpp
> +    : Rectangle(x, x, color) {}
Please also add a delegating constructor in Square

2020-10-29 13:18 UTC, ziobron commented on shapes/Rectangle.cpp
>  {}
Please also add a delegating constructor in Rectangle

2020-10-29 13:18 UTC, ziobron commented on shapes/main.cpp
> +std::function<bool(shared_ptr<Shape>)> areaLessThanX{[x{10}](shared_ptr<Shape> s) {
auto here as a type is enough. You only need to pass it to findFirstShapeMatchingPredicate as std::function.

2020-10-29 13:18 UTC, ziobron commented on shapes/main.cpp
>  }
this does not do what you was asked for:
> Write a function that allows inserting only subclasses of Shape to the collection

2020-11-12 18:12 UTC, niemarcin reviewed
Minor suggestion added

2020-11-12 18:12 UTC, niemarcin commented on shapes/Shape.hpp
> +    Color color_ = Color::Red;
```suggestion
    Color color_{Color::Red};
```
Should work fine as well :)

2020-11-14 21:16 UTC, ziobron commented
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4448, 4450, 4451, 4452] }

2020-11-14 21:16 UTC, closed without merging