Homework modern cpp #2
coders-school/modern-cpp pull request #26
Opened 2020-10-31 15:32 UTC by DamiXioR

2020-10-31 19:52 UTC, MaciejSalamonski approved these changes
Good but I think that delegating constructors are missing

2020-11-01 21:39 UTC, ziobron requested changes
There is a CI error: https://travis-ci.com/github/coders-school/modern-cpp/jobs/423283338

2020-11-01 21:39 UTC, ziobron commented on shapes/Circle.cpp
>      : r_(r)
no constructor delegation. It takes place when one constructor calls another of the same class on initializer list.

2020-11-01 21:39 UTC, ziobron commented on shapes/Rectangle.cpp
> -{}
constructor delegation missing

2020-11-01 21:39 UTC, ziobron commented on shapes/Square.cpp
>      : Rectangle(x, x)
constructor delegation is missing

2020-11-01 21:39 UTC, ziobron commented on shapes/main.cpp
> +    auto insertPosition = collection.emplace_back(shape);
not position, a reference to the inserted element is returned.

2020-11-01 21:39 UTC, ziobron commented on shapes/main.cpp
> +using SFINAE = std::enable_if<std::is_base_of<Circle, std::remove_reference_t<DerivedType>>::value>;
Hmm... Circle? We want to enable this overload for all classes that inherit from Shape, not Circle.
i'm not sure you should also take a type of this whole expression
```suggestion
using SFINAE = std::enable_if<std::is_base_of<Shape, std::remove_reference_t<DerivedType>>::value>::type;
```

2020-11-01 21:39 UTC, ziobron commented on shapes/main.cpp
> +auto insertSubclassOfShapes(Collection& collection, std::shared_ptr<DerivedType> shape)
shared_ptr can be taken by const &

2020-11-01 21:39 UTC, ziobron commented on shapes/main.cpp
> +    auto insertedIn = insertSubclassOfShapes<Rectangle>(shapes, std::make_shared<Rectangle>(50, 40, Color::Black));
does it compile?

2020-11-02 09:15 UTC, WBigaj reviewed
I have checked your code and have nothing to add that was not mentioned by previous reviewers.

2020-11-02 16:05 UTC, DamiXioR commented on shapes/main.cpp
> +    auto insertedIn = insertSubclassOfShapes<Rectangle>(shapes, std::make_shared<Rectangle>(50, 40, Color::Black));
i think it works now.

2020-11-03 11:34 UTC, ziobron requested changes

2020-11-03 11:34 UTC, ziobron commented on shapes/Circle.cpp
> -{}
You have removed this constructor, but you should use a delegation. I know that default argument version has the same behavior, but the idea here was to show constructor delegation feature.
You should leave this constructor and call below constructor on initializer list.
The same for other shapes.

2020-11-09 13:18 UTC, DamiXioR commented
Its everything allright :)?

2020-11-10 22:55 UTC, ziobron commented
I'm waiting for you to add a constructor delegation. Take a look at other's people solutions. Constructor delegation takes place when you call another constructor of the same class on initialization list.

2020-11-11 12:41 UTC, DamiXioR commented
> I'm waiting for you to add a constructor delegation. Take a look at other's people solutions. Constructor delegation takes place when you call another constructor of the same class on initialization list.

I think it's done.

2020-11-11 19:09 UTC, ziobron approved these changes

2020-11-11 19:10 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-11-11 19:10 UTC, closed without merging