Online2020 homework
coders-school/modern-cpp pull request #27
Opened 2020-10-31 17:39 UTC by MonikaZelechowska

zad 11. SFINAE  
       14. `alignas`, `alignof` 
       15. delegating constructors:
       16. lambda functions
       17. structured bindings
       18. variadic templates

2020-10-31 19:54 UTC, MaciejSalamonski requested changes
Good job +1

2020-11-01 23:16 UTC, ziobron requested changes
Delegating constructors are missing. This feature allows you to call other constructor of the same class on constructors initializer list.

2020-11-01 23:16 UTC, ziobron commented on shapes/main.cpp
> +    return std::shared_ptr<DerivedType>{new DerivedType{std::forward<Arguments>(args)...}};
```suggestion
    return std::make_shared<DerivedType>(std::forward<Arguments>(args)...);
```
your way is correct, but it's always better to allocate with make_shared

2020-11-02 09:31 UTC, WBigaj reviewed
Few suggestions from me.

2020-11-02 09:31 UTC, WBigaj commented on shapes/main.cpp
>              it->print();
```suggestion
    for (const auto& it : collection) {
        if (it) {
            it->print();
        }
    }
```

2020-11-02 09:31 UTC, WBigaj commented on shapes/main.cpp
>              cout << it->getArea() << std::endl;
```suggestion
    for (const auto& it : collection) {
        if (it) {
            cout << it->getArea() << '\n';
        }
    }
```

2020-11-03 11:53 UTC, ziobron requested changes
Constructor delegation is still missing. I know that a constructor with default arguments behave in the same way, but the idea behind this task was to learn constructor delegation. You need to call the constructor of the same class (not base class) on other's constructor initialization list like below:
```cpp
X::X(int a, double b, string c) {}
X::X(int a) : X(a, 2.0, "test") {}
```

2020-11-05 14:02 UTC, ziobron approved these changes

2020-11-05 14:02 UTC, ziobron commented
15 XP za Nowoczesny C++ SFINAE (4447)
5 XP za Nowoczesny C++ alignas (4448)
5 XP za Nowoczesny C++ delegating constructors (4449)
5 XP za Nowoczesny C++ lambda (4450)
5 XP za Nowoczesny C++ structured bindings (4451)
15 XP za Nowoczesny C++ variadic templates (4452)

{ "requirement_ids": [4447, 4448, 4449, 4450, 4451, 4452] }

2020-11-05 14:02 UTC, closed without merging