Normalizacja i ujednolicanie
coders-school/modern-cpp pull request #6
Opened 2020-08-10 08:30 UTC by MrMijagi

2020-08-10 17:16 UTC, ziobron requested changes

2020-08-10 17:16 UTC, ziobron commented on README.md
> +# Testowanie
```suggestion
# Nowoczesny C++
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
Wywal z readme przerwy :)
```suggestion

```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
Intro w sumie nic nie wnosi do tematu, do wywalenia
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on README.md
> +
```suggestion
```

2020-08-10 17:16 UTC, ziobron commented on module1/00_intro.md
> +### [Link to presentation on GitHub](https://github.com/coders-school/advanced_cpp/tree/master/md.modern_cpp_basic_features)
```suggestion
### [Link to presentation on GitHub](https://github.com/coders-school/modern-cpp/tree/master/module1)
```

2020-08-10 17:16 UTC, ziobron commented on module2/index.html
> +                    <h1>Modern C++ #1</h1>
```suggestion
                    <h1>Modern C++ #2</h1>
```

2020-08-10 17:16 UTC, ziobron commented on module3/index.html
> +            link.href = window.location.search.match( /print-pdf/gi ) ? '../../css/print/pdf.css' : '../css/print/paper.css';
```suggestion
            link.href = window.location.search.match( /print-pdf/gi ) ? '../../css/print/pdf.css' : '../../css/print/paper.css';
```

2020-08-10 17:16 UTC, ziobron commented on module3/index.html
> +                    <h1>Modern C++ #1</h1>
```suggestion
                    <h1>Modern C++ #3</h1>
```

2020-08-10 17:16 UTC, ziobron commented on module3/move_semantics_intro.md
> +</ul>
Można do MD skonwertować

2020-08-10 17:16 UTC, ziobron commented on module3/move_semantics_move_assignment_operator.md
> +## Usage of move semantics
Nazwa pliku nie pasuje. 
move_semantics_usage.md może być.

2020-08-10 17:16 UTC, ziobron commented on module3/move_semantics_copy_elision.md
> +## Knowledge check 🤯
Odtąd w dół może być oddzielny plik - move_semantics_knowledge_check.md

2020-08-10 17:16 UTC, ziobron commented on module3/move_semantics_reference_collapsing.md
> +<!-- .element: class="fragment fade-in" -->
Ten slajd przenieś na początek std_forward.md

2020-08-24 10:16 UTC, Penthurion reviewed
Nie widzę niczego, w czym mógłbym zasugerować poprawki/zmiany.

2020-09-01 20:05 UTC, merged